#!/usr/bin/env bash

capbash_parse_params()
{
  while
    (( $# > 0 ))
  do
    token="$1"
    shift
    case "$token" in

      (--path)
        if [[ -n "${1:-}" ]]
        then
          capbash_path="$1"
          shift
        else
          fail "--path must be followed by a path, e.g. /usr/local/bin."
        fi
        ;;

      (--capbash)
        if [[ -n "${1:-}" ]]
        then
          capbash_filename="$1"
          shift
        else
          fail "--capbash must be followed by a filename, e.g. /usr/local/bin/capbash."
        fi
        ;;


    esac
  done

  capbash_path=${capbash_path-/usr/local/bin}
  capbash_filename=${capbash_filename-${capbash_path}/capbash}
}

capbash_install()
{
  capbash_parse_params "$@"
  echo "Installing capbash into \"$capbash_filename\""
  curl -s -o "$capbash_filename" https://raw.githubusercontent.com/capbash/capbash/master/capbash
  chmod 755 "${capbash_filename}"
  echo "Done, to uninstall 'rm \"${capbash_filename}\"'."
}

capbash_install "$@"