#!/usr/bin/env bash

capbash_parse_params()
{
  while
    (( $# > 0 ))
  do
    token="$1"
    shift
    case "$token" in

      (--path)
        if [[ -n "${1:-}" ]]
        then
          capbash_path="$1"
          shift
        else
          fail "--path must be followed by a path."
        fi
        ;;

    esac
  done

  capbash_path=${capbash_path-/usr/local/bin}
}

capbash_install()
{
  capbash_parse_params "$@"
  echo "Installing capbash into $capbash_path"

  SCRIPT=$(cat <<EOF
#!/usr/bin/env bash
if [[ "\$1" == "new" ]]; then
  NAME=\${2-devops}
  if [[ -e \$NAME ]]; then
    echo "Directory \$NAME already exists, remove it and try again or pick another name please."
    exit 1
  else
    mkdir -p \$NAME
    (
      cd \$NAME &&
      git init
      mkdir -p ./submodules &&
      git submodule add https://github.com/aforward/capbash-bootstrap ./submodules/bootstrap &&
      ./submodules/bootstrap/bootstrap
    )
  fi

else
  # delegating to bootstrap
  ./submodules/bootstrap/capbash \$@
fi
EOF
  )

  printf "${SCRIPT}\n" > ${capbash_path}/capbash
  chmod 755 ${capbash_path}/capbash
  echo "Done, to uninstall 'rm ${capbash_path}/capbash'."
}

capbash_install "$@"